version: "3.9"
services:
  cypress-api:
    container_name: container-cypress-api
    depends_on:
      - cypress-db
    env_file: sorry_cypress/.env
    expose:
      - "4000"
    image: agoldis/sorry-cypress-api:latest
    networks:
      cypress:
        ipv4_address: 172.150.5.2
    profiles:
      - test
    restart: unless-stopped
  cypress-dashboard:
    container_name: container-cypress-dashboard
    depends_on:
      - cypress-api
      - cypress-db
    environment:
      GRAPHQL_SCHEMA_URL: http://172.150.5.2:4000
      PORT: 6749
    expose:
      - "6749"
    image: agoldis/sorry-cypress-dashboard:latest
    networks:
      test:
        ipv4_address: 172.150.0.2
      cypress:
        ipv4_address: 172.150.5.10
    profiles:
      - test
    restart: unless-stopped
  cypress-db:
    build:
      context: sorry_cypress/
      dockerfile: db.Dockerfile
    container_name: container-cypress-db
    expose:
      - "27017"
    networks:
      cypress:
        ipv4_address: 172.150.5.3
    profiles:
      - test
    restart: unless-stopped
    volumes:
      - type: volume
        source: volume-cypress-db
        target: /data
  cypress-director:
    container_name: container-cypress-director
    depends_on:
      - cypress-db
    env_file: sorry_cypress/.env
    environment:
      DASHBOARD_URL: http://172.150.0.2/
      EXECUTION_DRIVER: "../execution/mongo/driver"
      SCREENSHOTS_DRIVER: "../screenshots/dummy.driver"
    expose:
      - "1234"
    image: agoldis/sorry-cypress-director:latest
    networks:
      cypress:
        ipv4_address: 172.150.5.4
    profiles:
      - test
    restart: unless-stopped
networks:
  test:
    name: test-network
    ipam:
      config:
        - subnet: 172.150.0.0/24
  cypress:
    name: cypress-network
    ipam:
      config:
        - subnet: 172.150.5.0/24
volumes:
  volume-cypress-db: null
